### ISSUE TITLE
Module not found: Can't resolve '@/lib/utils'

### ISSUE THREAD

**Issue by skyblue1195s** [openai/interactive-textbook-demo#3]
I downloaded the repo and ran code, I saw the message 
failed to compile
./components/ui/accordion.tsx:7:0
Module not found: Can't resolve '@/lib/utils'
   5 | import { ChevronDown } from "lucide-react"
   6 | 
>  7 | import { cn } from "@/lib/utils"
   8 | 
   9 | const Accordion = AccordionPrimitive.Root
  10 | 

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./app/page.tsx
This error occurred during the build process and can only be dismissed by fixing the error.

I have checked folder, lib folder not existed

**Comment by cathykc** [comment]
Thanks for the call out! Included that folder. Let me know if you have any other issues.
